### ISSUE TITLE
SCK on PORTB PIN11

### ISSUE THREAD

**Issue by lxschwalb** [adafruit/Adafruit_ZeroI2S#9]
https://github.com/adafruit/Adafruit_ZeroI2S/blob/b71e73ed696f159538a8619d733474143901cf7e/Adafruit_ZeroI2S.cpp#L165

I think there might be a typo here. It should be `clockpin == 11`.

**Comment by lxschwalb** [comment]
and another small typo in the same file on line 193. I think it should be `// PA21` and not `// PA20`

**Comment by ladyada** [comment]
ooh can ya submit a PR to fix both? thanks :)

**Comment by lxschwalb** [comment]
Will do. I noticed something similar in the ZeroPDM library. I'll submit a PR there too

**Comment by ladyada** [comment]
yay!
